# Generated by Django 5.2.17 on 2026-10-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_funciones_y_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='MANUAL', max_length=20)),
                ('archivo', models.FileField(upload_to='backups/')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
