# Generated by Django 5.0.14 on 2026-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
