# Generated by Django 5.0.14 on 2026-10-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_referido_funciones_y_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='tipo',
            field=models.CharField(choices=[('QR', 'Código QR'), ('CUENTA_BANCARIA', 'Cuenta bancaria'), ('PASARELA', 'Pasarela de pago'), ('PAYPAL', 'PayPal')], max_length=20),
        ),
    ]
