# Generated by Django 5.0.14 on 2026-09-29 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_resumen_catalogo'),
        ('pedidos', '0006_alter_ordencompra_metodo_pago_alter_pago_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.producto'),
        ),
    ]
