# Generated by Django 5.0.14 on 2026-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedidoitem_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes_pago/'),
        ),
    ]
